"""
backend/models/db/models.py — SQLAlchemy ORM models.

All primary keys are UUID strings generated by the application layer
(uuid.uuid4()) before insertion so that async SQLAlchemy never needs to
round-trip to the DB just to learn the PK.
"""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    BigInteger,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.models.db.base import Base


# ---------------------------------------------------------------------------
# StoredFile
# ---------------------------------------------------------------------------

class StoredFile(Base):
    __tablename__ = "stored_files"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    original_name: Mapped[str] = mapped_column(String(512), nullable=False)
    storage_key: Mapped[str] = mapped_column(String(1024), nullable=False)
    storage_backend: Mapped[str] = mapped_column(String(64), nullable=False, default="local")
    content_type: Mapped[str | None] = mapped_column(String(256))
    size_bytes: Mapped[int | None] = mapped_column(BigInteger)
    uploaded_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


# ---------------------------------------------------------------------------
# PipelineJob
# ---------------------------------------------------------------------------

class PipelineJob(Base):
    __tablename__ = "pipeline_jobs"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    job_type: Mapped[str] = mapped_column(String(64), nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False, default="queued")
    current_step: Mapped[int | None] = mapped_column(Integer)
    total_steps: Mapped[int] = mapped_column(Integer, nullable=False, default=6)
    progress_pct: Mapped[int | None] = mapped_column(Integer)
    config: Mapped[dict | None] = mapped_column(JSONB)
    result: Mapped[dict | None] = mapped_column(JSONB)
    error_message: Mapped[str | None] = mapped_column(Text)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )


# ---------------------------------------------------------------------------
# Prospect
# ---------------------------------------------------------------------------

class Prospect(Base):
    __tablename__ = "prospects"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    draft_year: Mapped[int | None] = mapped_column(Integer)
    name: Mapped[str] = mapped_column(String(256), nullable=False)
    position: Mapped[str | None] = mapped_column(String(32))
    school: Mapped[str | None] = mapped_column(String(256))
    draft_round: Mapped[int | None] = mapped_column(Integer)
    draft_pick: Mapped[int | None] = mapped_column(Integer)
    height: Mapped[str | None] = mapped_column(String(16))
    weight: Mapped[int | None] = mapped_column(Integer)
    forty_time: Mapped[float | None] = mapped_column(Float)
    bench: Mapped[int | None] = mapped_column(Integer)
    vertical: Mapped[float | None] = mapped_column(Float)
    broad_jump: Mapped[int | None] = mapped_column(Integer)
    three_cone: Mapped[float | None] = mapped_column(Float)
    shuttle: Mapped[float | None] = mapped_column(Float)
    draft_grade: Mapped[float | None] = mapped_column(Float)
    board_rank: Mapped[int | None] = mapped_column(Integer)
    source: Mapped[str | None] = mapped_column(String(128))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    ratings: Mapped[list["ProspectRating"]] = relationship(
        "ProspectRating", back_populates="prospect", lazy="noload"
    )


# ---------------------------------------------------------------------------
# ProspectRating
# ---------------------------------------------------------------------------

class ProspectRating(Base):
    __tablename__ = "prospect_ratings"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    prospect_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), ForeignKey("prospects.id", ondelete="CASCADE"), nullable=False
    )
    draft_class_id: Mapped[str | None] = mapped_column(
        UUID(as_uuid=False), ForeignKey("draft_classes.id", ondelete="SET NULL")
    )
    llm_provider: Mapped[str | None] = mapped_column(String(64))
    generated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    is_manual: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    overall: Mapped[int | None] = mapped_column(Integer)
    speed: Mapped[int | None] = mapped_column(Integer)
    acceleration: Mapped[int | None] = mapped_column(Integer)
    agility: Mapped[int | None] = mapped_column(Integer)
    strength: Mapped[int | None] = mapped_column(Integer)
    awareness: Mapped[int | None] = mapped_column(Integer)
    throw_power: Mapped[int | None] = mapped_column(Integer)
    throw_accuracy: Mapped[int | None] = mapped_column(Integer)
    dev_trait: Mapped[str | None] = mapped_column(String(32))
    raw_llm_output: Mapped[dict | None] = mapped_column(JSONB)
    prompt_hash: Mapped[str | None] = mapped_column(String(64))

    prospect: Mapped["Prospect"] = relationship("Prospect", back_populates="ratings")


# ---------------------------------------------------------------------------
# DraftClass
# ---------------------------------------------------------------------------

class DraftClass(Base):
    __tablename__ = "draft_classes"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    name: Mapped[str] = mapped_column(String(256), nullable=False)
    season_year: Mapped[int | None] = mapped_column(Integer)
    description: Mapped[str | None] = mapped_column(Text)
    status: Mapped[str] = mapped_column(String(32), nullable=False, default="draft")
    exported_file_id: Mapped[str | None] = mapped_column(
        UUID(as_uuid=False), ForeignKey("stored_files.id", ondelete="SET NULL")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    exported_file: Mapped["StoredFile | None"] = relationship("StoredFile", lazy="noload")
    draft_class_prospects: Mapped[list["DraftClassProspect"]] = relationship(
        "DraftClassProspect", back_populates="draft_class", lazy="noload"
    )


# ---------------------------------------------------------------------------
# DraftClassProspect (join table)
# ---------------------------------------------------------------------------

class DraftClassProspect(Base):
    __tablename__ = "draft_class_prospects"

    draft_class_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("draft_classes.id", ondelete="CASCADE"),
        primary_key=True,
    )
    prospect_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("prospects.id", ondelete="CASCADE"),
        primary_key=True,
    )
    rating_id: Mapped[str | None] = mapped_column(
        UUID(as_uuid=False), ForeignKey("prospect_ratings.id", ondelete="SET NULL")
    )
    board_position: Mapped[int | None] = mapped_column(Integer)

    draft_class: Mapped["DraftClass"] = relationship(
        "DraftClass", back_populates="draft_class_prospects"
    )
    prospect: Mapped["Prospect"] = relationship("Prospect", lazy="noload")
    rating: Mapped["ProspectRating | None"] = relationship("ProspectRating", lazy="noload")


# ---------------------------------------------------------------------------
# Roster
# ---------------------------------------------------------------------------

class Roster(Base):
    __tablename__ = "rosters"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    name: Mapped[str] = mapped_column(String(256), nullable=False)
    madden_version: Mapped[str] = mapped_column(String(16), nullable=False, default="26")
    source_file_id: Mapped[str | None] = mapped_column(
        UUID(as_uuid=False), ForeignKey("stored_files.id", ondelete="SET NULL")
    )
    extracted_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    source_file: Mapped["StoredFile | None"] = relationship("StoredFile", lazy="noload")
    players: Mapped[list["RosterPlayer"]] = relationship(
        "RosterPlayer", back_populates="roster", lazy="noload"
    )


# ---------------------------------------------------------------------------
# RosterPlayer
# ---------------------------------------------------------------------------

class RosterPlayer(Base):
    __tablename__ = "roster_players"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    roster_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("rosters.id", ondelete="CASCADE"),
        nullable=False,
    )
    first_name: Mapped[str | None] = mapped_column(String(128))
    last_name: Mapped[str | None] = mapped_column(String(128))
    position: Mapped[str | None] = mapped_column(String(32))
    overall: Mapped[int | None] = mapped_column(Integer)
    age: Mapped[int | None] = mapped_column(Integer)
    dev_trait: Mapped[str | None] = mapped_column(String(32))
    ratings: Mapped[dict | None] = mapped_column(JSONB)
    contract_years: Mapped[int | None] = mapped_column(Integer)
    contract_salary: Mapped[float | None] = mapped_column(Float)
    cap_hit: Mapped[float | None] = mapped_column(Float)

    roster: Mapped["Roster"] = relationship("Roster", back_populates="players")


# ---------------------------------------------------------------------------
# Franchise
# ---------------------------------------------------------------------------

class Franchise(Base):
    __tablename__ = "franchises"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    name: Mapped[str] = mapped_column(String(256), nullable=False)
    team: Mapped[str | None] = mapped_column(String(64))
    madden_version: Mapped[str] = mapped_column(String(16), nullable=False, default="26")
    current_week: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    current_year: Mapped[int | None] = mapped_column(Integer)
    roster_id: Mapped[str | None] = mapped_column(
        UUID(as_uuid=False), ForeignKey("rosters.id", ondelete="SET NULL")
    )
    settings: Mapped[dict | None] = mapped_column(JSONB)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    roster: Mapped["Roster | None"] = relationship("Roster", lazy="noload")
    snapshots: Mapped[list["FranchiseSnapshot"]] = relationship(
        "FranchiseSnapshot", back_populates="franchise", lazy="noload"
    )
    advisor_sessions: Mapped[list["AdvisorSession"]] = relationship(
        "AdvisorSession", back_populates="franchise", lazy="noload"
    )


# ---------------------------------------------------------------------------
# FranchiseSnapshot
# ---------------------------------------------------------------------------

class FranchiseSnapshot(Base):
    __tablename__ = "franchise_snapshots"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    franchise_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("franchises.id", ondelete="CASCADE"),
        nullable=False,
    )
    week: Mapped[int | None] = mapped_column(Integer)
    year: Mapped[int | None] = mapped_column(Integer)
    snapshot_data: Mapped[dict | None] = mapped_column(JSONB)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    franchise: Mapped["Franchise"] = relationship("Franchise", back_populates="snapshots")


# ---------------------------------------------------------------------------
# AdvisorSession
# ---------------------------------------------------------------------------

class AdvisorSession(Base):
    __tablename__ = "advisor_sessions"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    franchise_id: Mapped[str] = mapped_column(
        UUID(as_uuid=False),
        ForeignKey("franchises.id", ondelete="CASCADE"),
        nullable=False,
    )
    messages: Mapped[dict | None] = mapped_column(JSONB)
    context_hash: Mapped[str | None] = mapped_column(String(64))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    franchise: Mapped["Franchise"] = relationship(
        "Franchise", back_populates="advisor_sessions"
    )


# ---------------------------------------------------------------------------
# LLMProviderConfig
# ---------------------------------------------------------------------------

class LLMProviderConfig(Base):
    __tablename__ = "llm_provider_configs"

    id: Mapped[str] = mapped_column(
        UUID(as_uuid=False), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    name: Mapped[str] = mapped_column(String(128), nullable=False, unique=True)
    provider_type: Mapped[str] = mapped_column(String(64), nullable=False)
    base_url: Mapped[str | None] = mapped_column(String(512))
    api_key_ref: Mapped[str | None] = mapped_column(String(256))
    default_model: Mapped[str | None] = mapped_column(String(128))
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    config: Mapped[dict | None] = mapped_column(JSONB)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
