"""
Default Madden 26 rating values per position.
Used to fill in non-key fields the LLM doesn't generate,
and as a fallback if LLM output is missing or invalid.
Values are tuned to match typical rookie ranges in the 2025 launch class.
"""

# fmt: off
POSITION_DEFAULTS = {
    "QB": {
        "overall": 68, "speed": 68, "acceleration": 72, "agility": 70,
        "strength": 52, "awareness": 65, "throwPower": 82, "throwAccuracy": 72,
        "throwAccuracyShort": 74, "throwAccuracyMid": 72, "throwAccuracyDeep": 68,
        "throwOnTheRun": 70, "throwUnderPressure": 68, "playAction": 65,
        "breakSack": 65, "tackle": 28, "hitPower": 28, "blockShedding": 28,
        "finesseMoves": 28, "powerMoves": 28, "pursuit": 28, "zoneCoverage": 28,
        "manCoverage": 28, "pressCoverage": 28, "playRecognition": 65,
        "jumping": 65, "catching": 40, "catchInTraffic": 38, "spectacularCatch": 38,
        "shortRouteRunning": 38, "mediumRouteRunning": 38, "deepRouteRunning": 38,
        "release": 38, "runBlock": 28, "passBlock": 28, "runBlockPower": 28,
        "runBlockFinesse": 28, "passBlockPower": 28, "passBlockFinesse": 28,
        "impactBlocking": 28, "leadBlock": 28, "jukeMove": 60, "spinMove": 50,
        "stiffArm": 50, "trucking": 48, "breakTackle": 50, "ballCarrierVision": 55,
        "changeOfDirection": 68, "carrying": 55, "kickPower": 38, "kickAccuracy": 38,
        "kickReturn": 38, "stamina": 78, "toughness": 72, "injury": 78,
        "morale": 75, "personality": 0, "devTrait": 0, "unkRating1": 50,
    },
    "HB": {
        "overall": 66, "speed": 86, "acceleration": 88, "agility": 84,
        "strength": 60, "awareness": 60, "throwPower": 28, "throwAccuracy": 28,
        "throwAccuracyShort": 28, "throwAccuracyMid": 28, "throwAccuracyDeep": 28,
        "throwOnTheRun": 28, "throwUnderPressure": 28, "playAction": 28,
        "breakSack": 28, "tackle": 38, "hitPower": 40, "blockShedding": 28,
        "finesseMoves": 28, "powerMoves": 28, "pursuit": 38, "zoneCoverage": 28,
        "manCoverage": 28, "pressCoverage": 28, "playRecognition": 58,
        "jumping": 72, "catching": 65, "catchInTraffic": 60, "spectacularCatch": 55,
        "shortRouteRunning": 55, "mediumRouteRunning": 50, "deepRouteRunning": 48,
        "release": 50, "runBlock": 38, "passBlock": 38, "runBlockPower": 35,
        "runBlockFinesse": 35, "passBlockPower": 35, "passBlockFinesse": 35,
        "impactBlocking": 35, "leadBlock": 35, "jukeMove": 82, "spinMove": 75,
        "stiffArm": 70, "trucking": 72, "breakTackle": 72, "ballCarrierVision": 72,
        "changeOfDirection": 84, "carrying": 82, "kickPower": 38, "kickAccuracy": 38,
        "kickReturn": 68, "stamina": 82, "toughness": 75, "injury": 78,
        "morale": 75, "personality": 0, "devTrait": 0, "unkRating1": 50,
    },
    "FB": {
        "overall": 64, "speed": 70, "acceleration": 72, "agility": 66,
        "strength": 72, "awareness": 62, "throwPower": 28, "throwAccuracy": 28,
        "throwAccuracyShort": 28, "throwAccuracyMid": 28, "throwAccuracyDeep": 28,
        "throwOnTheRun": 28, "throwUnderPressure": 28, "playAction": 28,
        "breakSack": 28, "tackle": 50, "hitPower": 55, "blockShedding": 28,
        "finesseMoves": 28, "powerMoves": 28, "pursuit": 45, "zoneCoverage": 28,
        "manCoverage": 28, "pressCoverage": 28, "playRecognition": 62,
        "jumping": 62, "catching": 60, "catchInTraffic": 55, "spectacularCatch": 48,
        "shortRouteRunning": 50, "mediumRouteRunning": 45, "deepRouteRunning": 40,
        "release": 45, "runBlock": 72, "passBlock": 68, "runBlockPower": 70,
        "runBlockFinesse": 62, "passBlockPower": 65, "passBlockFinesse": 60,
        "impactBlocking": 72, "leadBlock": 74, "jukeMove": 55, "spinMove": 50,
        "stiffArm": 58, "trucking": 68, "breakTackle": 62, "ballCarrierVision": 60,
        "changeOfDirection": 62, "carrying": 68, "kickPower": 38, "kickAccuracy": 38,
        "kickReturn": 40, "stamina": 80, "toughness": 78, "injury": 78,
        "morale": 75, "personality": 0, "devTrait": 0, "unkRating1": 50,
    },
    "WR": {
        "overall": 67, "speed": 90, "acceleration": 92, "agility": 86,
        "strength": 50, "awareness": 60, "throwPower": 28, "throwAccuracy": 28,
        "throwAccuracyShort": 28, "throwAccuracyMid": 28, "throwAccuracyDeep": 28,
        "throwOnTheRun": 28, "throwUnderPressure": 28, "playAction": 28,
        "breakSack": 28, "tackle": 28, "hitPower": 28, "blockShedding": 28,
        "finesseMoves": 28, "powerMoves": 28, "pursuit": 28, "zoneCoverage": 28,
        "manCoverage": 28, "pressCoverage": 28, "playRecognition": 60,
        "jumping": 85, "catching": 82, "catchInTraffic": 75, "spectacularCatch": 78,
        "shortRouteRunning": 72, "mediumRouteRunning": 70, "deepRouteRunning": 68,
        "release": 75, "runBlock": 38, "passBlock": 38, "runBlockPower": 35,
        "runBlockFinesse": 35, "passBlockPower": 35, "passBlockFinesse": 35,
        "impactBlocking": 35, "leadBlock": 35, "jukeMove": 78, "spinMove": 65,
        "stiffArm": 55, "trucking": 48, "breakTackle": 55, "ballCarrierVision": 60,
        "changeOfDirection": 86, "carrying": 72, "kickPower": 38, "kickAccuracy": 38,
        "kickReturn": 65, "stamina": 82, "toughness": 72, "injury": 78,
        "morale": 75, "personality": 0, "devTrait": 0, "unkRating1": 50,
    },
    "TE": {
        "overall": 65, "speed": 76, "acceleration": 78, "agility": 72,
        "strength": 68, "awareness": 60, "throwPower": 28, "throwAccuracy": 28,
        "throwAccuracyShort": 28, "throwAccuracyMid": 28, "throwAccuracyDeep": 28,
        "throwOnTheRun": 28, "throwUnderPressure": 28, "playAction": 28,
        "breakSack": 28, "tackle": 45, "hitPower": 48, "blockShedding": 28,
        "finesseMoves": 28, "powerMoves": 28, "pursuit": 38, "zoneCoverage": 28,
        "manCoverage": 28, "pressCoverage": 28, "playRecognition": 60,
        "jumping": 75, "catching": 76, "catchInTraffic": 72, "spectacularCatch": 65,
        "shortRouteRunning": 65, "mediumRouteRunning": 62, "deepRouteRunning": 58,
        "release": 62, "runBlock": 68, "passBlock": 62, "runBlockPower": 65,
        "runBlockFinesse": 58, "passBlockPower": 60, "passBlockFinesse": 55,
        "impactBlocking": 65, "leadBlock": 60, "jukeMove": 62, "spinMove": 52,
        "stiffArm": 58, "trucking": 62, "breakTackle": 60, "ballCarrierVision": 58,
        "changeOfDirection": 70, "carrying": 68, "kickPower": 38, "kickAccuracy": 38,
        "kickReturn": 42, "stamina": 80, "toughness": 76, "injury": 78,
        "morale": 75, "personality": 0, "devTrait": 0, "unkRating1": 50,
    },
    "T": {
        "overall": 65, "speed": 62, "acceleration": 64, "agility": 58,
        "strength": 78, "awareness": 62, "throwPower": 28, "throwAccuracy": 28,
        "throwAccuracyShort": 28, "throwAccuracyMid": 28, "throwAccuracyDeep": 28,
        "throwOnTheRun": 28, "throwUnderPressure": 28, "playAction": 28,
        "breakSack": 28, "tackle": 38, "hitPower": 38, "blockShedding": 28,
        "finesseMoves": 28, "powerMoves": 28, "pursuit": 28, "zoneCoverage": 28,
        "manCoverage": 28, "pressCoverage": 28, "playRecognition": 62,
        "jumping": 55, "catching": 28, "catchInTraffic": 28, "spectacularCatch": 28,
        "shortRouteRunning": 28, "mediumRouteRunning": 28, "deepRouteRunning": 28,
        "release": 28, "runBlock": 72, "passBlock": 72, "runBlockPower": 72,
        "runBlockFinesse": 65, "passBlockPower": 68, "passBlockFinesse": 70,
        "impactBlocking": 72, "leadBlock": 60, "jukeMove": 28, "spinMove": 28,
        "stiffArm": 28, "trucking": 28, "breakTackle": 28, "ballCarrierVision": 28,
        "changeOfDirection": 55, "carrying": 28, "kickPower": 38, "kickAccuracy": 38,
        "kickReturn": 38, "stamina": 80, "toughness": 78, "injury": 78,
        "morale": 75, "personality": 0, "devTrait": 0, "unkRating1": 50,
    },
    "G": {
        "overall": 64, "speed": 56, "acceleration": 58, "agility": 54,
        "strength": 80, "awareness": 62, "throwPower": 28, "throwAccuracy": 28,
        "throwAccuracyShort": 28, "throwAccuracyMid": 28, "throwAccuracyDeep": 28,
        "throwOnTheRun": 28, "throwUnderPressure": 28, "playAction": 28,
        "breakSack": 28, "tackle": 38, "hitPower": 38, "blockShedding": 28,
        "finesseMoves": 28, "powerMoves": 28, "pursuit": 28, "zoneCoverage": 28,
        "manCoverage": 28, "pressCoverage": 28, "playRecognition": 62,
        "jumping": 50, "catching": 28, "catchInTraffic": 28, "spectacularCatch": 28,
        "shortRouteRunning": 28, "mediumRouteRunning": 28, "deepRouteRunning": 28,
        "release": 28, "runBlock": 74, "passBlock": 70, "runBlockPower": 74,
        "runBlockFinesse": 65, "passBlockPower": 68, "passBlockFinesse": 66,
        "impactBlocking": 74, "leadBlock": 65, "jukeMove": 28, "spinMove": 28,
        "stiffArm": 28, "trucking": 28, "breakTackle": 28, "ballCarrierVision": 28,
        "changeOfDirection": 52, "carrying": 28, "kickPower": 38, "kickAccuracy": 38,
        "kickReturn": 38, "stamina": 80, "toughness": 78, "injury": 78,
        "morale": 75, "personality": 0, "devTrait": 0, "unkRating1": 50,
    },
    "C": {
        "overall": 63, "speed": 54, "acceleration": 56, "agility": 52,
        "strength": 80, "awareness": 65, "throwPower": 28, "throwAccuracy": 28,
        "throwAccuracyShort": 28, "throwAccuracyMid": 28, "throwAccuracyDeep": 28,
        "throwOnTheRun": 28, "throwUnderPressure": 28, "playAction": 28,
        "breakSack": 28, "tackle": 38, "hitPower": 38, "blockShedding": 28,
        "finesseMoves": 28, "powerMoves": 28, "pursuit": 28, "zoneCoverage": 28,
        "manCoverage": 28, "pressCoverage": 28, "playRecognition": 65,
        "jumping": 50, "catching": 28, "catchInTraffic": 28, "spectacularCatch": 28,
        "shortRouteRunning": 28, "mediumRouteRunning": 28, "deepRouteRunning": 28,
        "release": 28, "runBlock": 72, "passBlock": 70, "runBlockPower": 72,
        "runBlockFinesse": 65, "passBlockPower": 68, "passBlockFinesse": 66,
        "impactBlocking": 72, "leadBlock": 62, "jukeMove": 28, "spinMove": 28,
        "stiffArm": 28, "trucking": 28, "breakTackle": 28, "ballCarrierVision": 28,
        "changeOfDirection": 50, "carrying": 28, "kickPower": 38, "kickAccuracy": 38,
        "kickReturn": 38, "stamina": 80, "toughness": 78, "injury": 78,
        "morale": 75, "personality": 0, "devTrait": 0, "unkRating1": 50,
    },
    "DE": {
        "overall": 66, "speed": 80, "acceleration": 84, "agility": 76,
        "strength": 75, "awareness": 58, "throwPower": 28, "throwAccuracy": 28,
        "throwAccuracyShort": 28, "throwAccuracyMid": 28, "throwAccuracyDeep": 28,
        "throwOnTheRun": 28, "throwUnderPressure": 28, "playAction": 28,
        "breakSack": 72, "tackle": 70, "hitPower": 72, "blockShedding": 72,
        "finesseMoves": 70, "powerMoves": 68, "pursuit": 72, "zoneCoverage": 38,
        "manCoverage": 38, "pressCoverage": 38, "playRecognition": 60,
        "jumping": 65, "catching": 28, "catchInTraffic": 28, "spectacularCatch": 28,
        "shortRouteRunning": 28, "mediumRouteRunning": 28, "deepRouteRunning": 28,
        "release": 28, "runBlock": 28, "passBlock": 28, "runBlockPower": 28,
        "runBlockFinesse": 28, "passBlockPower": 28, "passBlockFinesse": 28,
        "impactBlocking": 28, "leadBlock": 28, "jukeMove": 28, "spinMove": 28,
        "stiffArm": 28, "trucking": 28, "breakTackle": 28, "ballCarrierVision": 28,
        "changeOfDirection": 72, "carrying": 28, "kickPower": 38, "kickAccuracy": 38,
        "kickReturn": 38, "stamina": 80, "toughness": 76, "injury": 78,
        "morale": 75, "personality": 0, "devTrait": 0, "unkRating1": 50,
    },
    "DT": {
        "overall": 65, "speed": 70, "acceleration": 72, "agility": 65,
        "strength": 82, "awareness": 58, "throwPower": 28, "throwAccuracy": 28,
        "throwAccuracyShort": 28, "throwAccuracyMid": 28, "throwAccuracyDeep": 28,
        "throwOnTheRun": 28, "throwUnderPressure": 28, "playAction": 28,
        "breakSack": 68, "tackle": 72, "hitPower": 74, "blockShedding": 74,
        "finesseMoves": 65, "powerMoves": 72, "pursuit": 68, "zoneCoverage": 38,
        "manCoverage": 38, "pressCoverage": 38, "playRecognition": 60,
        "jumping": 60, "catching": 28, "catchInTraffic": 28, "spectacularCatch": 28,
        "shortRouteRunning": 28, "mediumRouteRunning": 28, "deepRouteRunning": 28,
        "release": 28, "runBlock": 28, "passBlock": 28, "runBlockPower": 28,
        "runBlockFinesse": 28, "passBlockPower": 28, "passBlockFinesse": 28,
        "impactBlocking": 28, "leadBlock": 28, "jukeMove": 28, "spinMove": 28,
        "stiffArm": 28, "trucking": 28, "breakTackle": 28, "ballCarrierVision": 28,
        "changeOfDirection": 62, "carrying": 28, "kickPower": 38, "kickAccuracy": 38,
        "kickReturn": 38, "stamina": 80, "toughness": 78, "injury": 78,
        "morale": 75, "personality": 0, "devTrait": 0, "unkRating1": 50,
    },
    "OLB": {
        "overall": 65, "speed": 82, "acceleration": 84, "agility": 78,
        "strength": 68, "awareness": 60, "throwPower": 28, "throwAccuracy": 28,
        "throwAccuracyShort": 28, "throwAccuracyMid": 28, "throwAccuracyDeep": 28,
        "throwOnTheRun": 28, "throwUnderPressure": 28, "playAction": 28,
        "breakSack": 68, "tackle": 72, "hitPower": 72, "blockShedding": 65,
        "finesseMoves": 62, "powerMoves": 60, "pursuit": 72, "zoneCoverage": 65,
        "manCoverage": 62, "pressCoverage": 58, "playRecognition": 62,
        "jumping": 68, "catching": 28, "catchInTraffic": 28, "spectacularCatch": 28,
        "shortRouteRunning": 28, "mediumRouteRunning": 28, "deepRouteRunning": 28,
        "release": 28, "runBlock": 28, "passBlock": 28, "runBlockPower": 28,
        "runBlockFinesse": 28, "passBlockPower": 28, "passBlockFinesse": 28,
        "impactBlocking": 28, "leadBlock": 28, "jukeMove": 28, "spinMove": 28,
        "stiffArm": 28, "trucking": 28, "breakTackle": 28, "ballCarrierVision": 28,
        "changeOfDirection": 75, "carrying": 28, "kickPower": 38, "kickAccuracy": 38,
        "kickReturn": 38, "stamina": 80, "toughness": 75, "injury": 78,
        "morale": 75, "personality": 0, "devTrait": 0, "unkRating1": 50,
    },
    "MLB": {
        "overall": 65, "speed": 76, "acceleration": 78, "agility": 72,
        "strength": 72, "awareness": 65, "throwPower": 28, "throwAccuracy": 28,
        "throwAccuracyShort": 28, "throwAccuracyMid": 28, "throwAccuracyDeep": 28,
        "throwOnTheRun": 28, "throwUnderPressure": 28, "playAction": 28,
        "breakSack": 58, "tackle": 76, "hitPower": 74, "blockShedding": 60,
        "finesseMoves": 55, "powerMoves": 58, "pursuit": 74, "zoneCoverage": 68,
        "manCoverage": 65, "pressCoverage": 58, "playRecognition": 66,
        "jumping": 65, "catching": 28, "catchInTraffic": 28, "spectacularCatch": 28,
        "shortRouteRunning": 28, "mediumRouteRunning": 28, "deepRouteRunning": 28,
        "release": 28, "runBlock": 28, "passBlock": 28, "runBlockPower": 28,
        "runBlockFinesse": 28, "passBlockPower": 28, "passBlockFinesse": 28,
        "impactBlocking": 28, "leadBlock": 28, "jukeMove": 28, "spinMove": 28,
        "stiffArm": 28, "trucking": 28, "breakTackle": 28, "ballCarrierVision": 28,
        "changeOfDirection": 70, "carrying": 28, "kickPower": 38, "kickAccuracy": 38,
        "kickReturn": 38, "stamina": 80, "toughness": 76, "injury": 78,
        "morale": 75, "personality": 0, "devTrait": 0, "unkRating1": 50,
    },
    "CB": {
        "overall": 67, "speed": 91, "acceleration": 93, "agility": 88,
        "strength": 50, "awareness": 60, "throwPower": 28, "throwAccuracy": 28,
        "throwAccuracyShort": 28, "throwAccuracyMid": 28, "throwAccuracyDeep": 28,
        "throwOnTheRun": 28, "throwUnderPressure": 28, "playAction": 28,
        "breakSack": 38, "tackle": 58, "hitPower": 58, "blockShedding": 28,
        "finesseMoves": 28, "powerMoves": 28, "pursuit": 68, "zoneCoverage": 72,
        "manCoverage": 74, "pressCoverage": 68, "playRecognition": 62,
        "jumping": 86, "catching": 55, "catchInTraffic": 50, "spectacularCatch": 55,
        "shortRouteRunning": 38, "mediumRouteRunning": 38, "deepRouteRunning": 38,
        "release": 72, "runBlock": 28, "passBlock": 28, "runBlockPower": 28,
        "runBlockFinesse": 28, "passBlockPower": 28, "passBlockFinesse": 28,
        "impactBlocking": 28, "leadBlock": 28, "jukeMove": 72, "spinMove": 60,
        "stiffArm": 50, "trucking": 45, "breakTackle": 48, "ballCarrierVision": 55,
        "changeOfDirection": 88, "carrying": 55, "kickPower": 38, "kickAccuracy": 38,
        "kickReturn": 72, "stamina": 82, "toughness": 72, "injury": 78,
        "morale": 75, "personality": 0, "devTrait": 0, "unkRating1": 50,
    },
    "FS": {
        "overall": 65, "speed": 88, "acceleration": 90, "agility": 84,
        "strength": 52, "awareness": 64, "throwPower": 28, "throwAccuracy": 28,
        "throwAccuracyShort": 28, "throwAccuracyMid": 28, "throwAccuracyDeep": 28,
        "throwOnTheRun": 28, "throwUnderPressure": 28, "playAction": 28,
        "breakSack": 40, "tackle": 62, "hitPower": 62, "blockShedding": 28,
        "finesseMoves": 28, "powerMoves": 28, "pursuit": 70, "zoneCoverage": 74,
        "manCoverage": 68, "pressCoverage": 60, "playRecognition": 66,
        "jumping": 82, "catching": 58, "catchInTraffic": 52, "spectacularCatch": 55,
        "shortRouteRunning": 38, "mediumRouteRunning": 38, "deepRouteRunning": 38,
        "release": 62, "runBlock": 28, "passBlock": 28, "runBlockPower": 28,
        "runBlockFinesse": 28, "passBlockPower": 28, "passBlockFinesse": 28,
        "impactBlocking": 28, "leadBlock": 28, "jukeMove": 68, "spinMove": 55,
        "stiffArm": 48, "trucking": 45, "breakTackle": 50, "ballCarrierVision": 58,
        "changeOfDirection": 82, "carrying": 52, "kickPower": 38, "kickAccuracy": 38,
        "kickReturn": 65, "stamina": 82, "toughness": 72, "injury": 78,
        "morale": 75, "personality": 0, "devTrait": 0, "unkRating1": 50,
    },
    "SS": {
        "overall": 65, "speed": 84, "acceleration": 86, "agility": 80,
        "strength": 62, "awareness": 62, "throwPower": 28, "throwAccuracy": 28,
        "throwAccuracyShort": 28, "throwAccuracyMid": 28, "throwAccuracyDeep": 28,
        "throwOnTheRun": 28, "throwUnderPressure": 28, "playAction": 28,
        "breakSack": 44, "tackle": 70, "hitPower": 72, "blockShedding": 28,
        "finesseMoves": 28, "powerMoves": 28, "pursuit": 72, "zoneCoverage": 68,
        "manCoverage": 65, "pressCoverage": 58, "playRecognition": 64,
        "jumping": 78, "catching": 55, "catchInTraffic": 50, "spectacularCatch": 52,
        "shortRouteRunning": 38, "mediumRouteRunning": 38, "deepRouteRunning": 38,
        "release": 60, "runBlock": 28, "passBlock": 28, "runBlockPower": 28,
        "runBlockFinesse": 28, "passBlockPower": 28, "passBlockFinesse": 28,
        "impactBlocking": 28, "leadBlock": 28, "jukeMove": 65, "spinMove": 52,
        "stiffArm": 52, "trucking": 55, "breakTackle": 55, "ballCarrierVision": 58,
        "changeOfDirection": 78, "carrying": 52, "kickPower": 38, "kickAccuracy": 38,
        "kickReturn": 58, "stamina": 80, "toughness": 75, "injury": 78,
        "morale": 75, "personality": 0, "devTrait": 0, "unkRating1": 50,
    },
    "K": {
        "overall": 65, "speed": 50, "acceleration": 52, "agility": 50,
        "strength": 50, "awareness": 60, "throwPower": 28, "throwAccuracy": 28,
        "throwAccuracyShort": 28, "throwAccuracyMid": 28, "throwAccuracyDeep": 28,
        "throwOnTheRun": 28, "throwUnderPressure": 28, "playAction": 28,
        "breakSack": 28, "tackle": 28, "hitPower": 28, "blockShedding": 28,
        "finesseMoves": 28, "powerMoves": 28, "pursuit": 28, "zoneCoverage": 28,
        "manCoverage": 28, "pressCoverage": 28, "playRecognition": 60,
        "jumping": 50, "catching": 28, "catchInTraffic": 28, "spectacularCatch": 28,
        "shortRouteRunning": 28, "mediumRouteRunning": 28, "deepRouteRunning": 28,
        "release": 28, "runBlock": 28, "passBlock": 28, "runBlockPower": 28,
        "runBlockFinesse": 28, "passBlockPower": 28, "passBlockFinesse": 28,
        "impactBlocking": 28, "leadBlock": 28, "jukeMove": 28, "spinMove": 28,
        "stiffArm": 28, "trucking": 28, "breakTackle": 28, "ballCarrierVision": 28,
        "changeOfDirection": 48, "carrying": 28, "kickPower": 82, "kickAccuracy": 80,
        "kickReturn": 38, "stamina": 78, "toughness": 70, "injury": 78,
        "morale": 75, "personality": 0, "devTrait": 0, "unkRating1": 50,
    },
    "P": {
        "overall": 65, "speed": 50, "acceleration": 52, "agility": 50,
        "strength": 50, "awareness": 60, "throwPower": 28, "throwAccuracy": 28,
        "throwAccuracyShort": 28, "throwAccuracyMid": 28, "throwAccuracyDeep": 28,
        "throwOnTheRun": 28, "throwUnderPressure": 28, "playAction": 28,
        "breakSack": 28, "tackle": 28, "hitPower": 28, "blockShedding": 28,
        "finesseMoves": 28, "powerMoves": 28, "pursuit": 28, "zoneCoverage": 28,
        "manCoverage": 28, "pressCoverage": 28, "playRecognition": 60,
        "jumping": 50, "catching": 28, "catchInTraffic": 28, "spectacularCatch": 28,
        "shortRouteRunning": 28, "mediumRouteRunning": 28, "deepRouteRunning": 28,
        "release": 28, "runBlock": 28, "passBlock": 28, "runBlockPower": 28,
        "runBlockFinesse": 28, "passBlockPower": 28, "passBlockFinesse": 28,
        "impactBlocking": 28, "leadBlock": 28, "jukeMove": 28, "spinMove": 28,
        "stiffArm": 28, "trucking": 28, "breakTackle": 28, "ballCarrierVision": 28,
        "changeOfDirection": 48, "carrying": 28, "kickPower": 82, "kickAccuracy": 80,
        "kickReturn": 38, "stamina": 78, "toughness": 70, "injury": 78,
        "morale": 75, "personality": 0, "devTrait": 0, "unkRating1": 50,
    },
    "LS": {
        "overall": 62, "speed": 52, "acceleration": 54, "agility": 50,
        "strength": 65, "awareness": 65, "throwPower": 28, "throwAccuracy": 28,
        "throwAccuracyShort": 28, "throwAccuracyMid": 28, "throwAccuracyDeep": 28,
        "throwOnTheRun": 28, "throwUnderPressure": 28, "playAction": 28,
        "breakSack": 28, "tackle": 38, "hitPower": 38, "blockShedding": 28,
        "finesseMoves": 28, "powerMoves": 28, "pursuit": 28, "zoneCoverage": 28,
        "manCoverage": 28, "pressCoverage": 28, "playRecognition": 65,
        "jumping": 50, "catching": 28, "catchInTraffic": 28, "spectacularCatch": 28,
        "shortRouteRunning": 28, "mediumRouteRunning": 28, "deepRouteRunning": 28,
        "release": 28, "runBlock": 55, "passBlock": 55, "runBlockPower": 55,
        "runBlockFinesse": 50, "passBlockPower": 52, "passBlockFinesse": 50,
        "impactBlocking": 55, "leadBlock": 50, "jukeMove": 28, "spinMove": 28,
        "stiffArm": 28, "trucking": 28, "breakTackle": 28, "ballCarrierVision": 28,
        "changeOfDirection": 48, "carrying": 28, "kickPower": 38, "kickAccuracy": 38,
        "kickReturn": 38, "stamina": 78, "toughness": 72, "injury": 78,
        "morale": 75, "personality": 0, "devTrait": 0, "unkRating1": 50,
    },
}

# Aliases for positions not in POSITION_DEFAULTS
POSITION_ALIASES = {
    "RB":   "HB",
    "OT":   "T",
    "LT":   "T",
    "RT":   "T",
    "OG":   "G",
    "LG":   "G",
    "RG":   "G",
    "NT":   "DT",
    "EDGE": "DE",
    "ILB":  "MLB",
    "LB":   "OLB",
    "S":    "FS",
    "DB":   "CB",
    "PK":   "K",
}


def get_defaults(pos: str) -> dict:
    """Return a copy of position defaults, resolving aliases."""
    pos = pos.upper()
    pos = POSITION_ALIASES.get(pos, pos)
    return dict(POSITION_DEFAULTS.get(pos, POSITION_DEFAULTS["QB"]))
